name = input ('Whats your Name? ')
upp = name.upper()
print('Uppercase name: {}'.format(upp))
low = name.lower()
print('Lowercase name: {}'.format(low))
splited = name.split()
n1 = name.replace(' ',"")
nletter = len(n1)
print('Number of letters of your name: {}'.format(nletter))
n1splited = len(splited[0])
print('Number of letters of your Firs name: {}'.format(n1splited))
